name: inventory
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.4
  flutter_screenutil: ^5.9.3
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  flutter_bloc: ^9.1.1
  cloud_firestore: ^6.3.0
  google_sign_in: ^5.4.4
  firebase_messaging: ^16.2.0
  lottie: ^3.3.3
  flutter_native_splash: ^2.4.7
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/inventory.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: appFont
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
