// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2R6xjGA1h-kzJ5ioCy5ij8RKpXRZxkZA',
    appId: '1:604181044152:web:e3cd916ca00fa48d404d4d',
    messagingSenderId: '604181044152',
    projectId: 'inventory-a4f66',
    authDomain: 'inventory-a4f66.firebaseapp.com',
    storageBucket: 'inventory-a4f66.firebasestorage.app',
    measurementId: 'G-JN5028LHPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACSV9q7fa9YPsgur84mrI5xItl3_b08Ec',
    appId: '1:604181044152:android:b30565a51c243318404d4d',
    messagingSenderId: '604181044152',
    projectId: 'inventory-a4f66',
    storageBucket: 'inventory-a4f66.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2R6xjGA1h-kzJ5ioCy5ij8RKpXRZxkZA',
    appId: '1:604181044152:web:8ce80d266c7c0ac6404d4d',
    messagingSenderId: '604181044152',
    projectId: 'inventory-a4f66',
    authDomain: 'inventory-a4f66.firebaseapp.com',
    storageBucket: 'inventory-a4f66.firebasestorage.app',
    measurementId: 'G-LSRR3NGZ9R',
  );
}
